baseURL = "https://www.hitopper.top/"
languageCode = "zh-cn"
title = "HI-TOPPER"
theme = "PaperMod"

[params]
  author = "HI-TOPPER"
  description = "心と体を温めるアーティスト"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  copyright = "Powered by Hugo & PaperMod & hitopper"

[[menu.main]]
  name = "ABOUT US"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "酒豪道場"
  url = "/dojo/"
  weight = 2
